services:
  caddy:
    container_name: caddy
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./etc/caddy
        target: /etc/caddy
      - type: bind
        source: /mnt/nas/localnet/caddy/data
        target: /data
      - type: bind
        source: /mnt/nas/localnet/caddy/config
        target: /config
    ports:
      - "80:80"
      - "443:443"
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    name: reverse-proxy
    external: true
